apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: build-task
spec:
  inputs:
    params:
      - name: gheToken
        description: the API token for cloning from GHE
      - name: task-pvc
        description: the output pvc
      - name: repository
        description: the git repo
      - name: revision
        description: the revision
        default: master
      - name: apikey
        description: the ibmcloud api key
      - name: api
        description: the ibmcloud api endpoint
        default: "https://cloud.ibm.com"
      - name: registryNamespace
        description: the ibmcloud registry namespace
      - name: imageName
        description: the base image name
        default: "hello-containers-tekton"
      - name: registryRegion
        description: the ibmcloud registry region
  steps:
    - name: config-git
      image: alpine/git
      env:
        - name: GHE_TOKEN
          value: $(inputs.params.gheToken
      command: ["/bin/sh", "-c"]
      args:
        - set -e -o pipefail;
          git config --global url."https://$GHE_TOKEN:x-oauth-basic@github.ibm.com/".insteadOf "https://github.ibm.com/";
    - name: clone-repo
      image: alpine/git
      env:
        - name: REPOSITORY
          value: $(inputs.params.repository)
        - name: REVISION
          value: $(inputs.params.revision)
      command: ["/bin/sh", "-c"]
      args:
        - set -e -o pipefail;
          echo "Cloning $REPOSITORY";
          git clone -q -b $REVISION $REPOSITORY .;
